name: Docker Image CI/CD

on:
  push:
    branches: [ "main" ]
    tags: 
      - '*'
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: main
        fetch-depth: 0
    - name: Get Git Tag
      id: get_tag
      run: |
        echo "Setting tag..."
        git tag
        TAG=$(git describe --abbrev=0)
        echo "TAG=$TAG" >> $GITHUB_ENV
        
    - name: Use Git Tag in Workflow
      run: |
        echo "The tag is $TAG"
